"""add railway

Revision ID: f4d78170d6be
Revises: 
Create Date: 2025-06-23 16:08:42.956900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d78170d6be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pengguna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('kata_sandi', sa.String(length=255), nullable=False),
    sa.Column('peran', sa.Enum('siswa', 'guru', 'admin', name='peranenum'), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.Column('diperbarui_pada', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rekomendasi_gaya_belajar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('gaya_belajar', sa.String(length=100), nullable=False),
    sa.Column('penjelasan', sa.Text(), nullable=False),
    sa.Column('rekomendasi', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kategori', 'gaya_belajar', name='uq_kategori_gaya')
    )
    op.create_index('idx_kategori_gaya', 'rekomendasi_gaya_belajar', ['kategori', 'gaya_belajar'], unique=False)
    op.create_table('sekolah',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama_sekolah', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_sekolah'),
    sa.UniqueConstraint('nama_sekolah', name='uq_nama_sekolah')
    )
    op.create_index('idx_nama_sekolah', 'sekolah', ['nama_sekolah'], unique=False)
    op.create_table('soal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('pilihan_a', sa.Text(), nullable=False),
    sa.Column('pilihan_b', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pengguna')
    )
    op.create_table('guru',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('tingkat_pendidikan', sa.String(length=100), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pengguna'),
    sa.UniqueConstraint('nip')
    )
    op.create_table('hasil_gaya_belajar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('skor_pemrosesan', sa.Integer(), nullable=False),
    sa.Column('kategori_pemrosesan', sa.String(length=20), nullable=False),
    sa.Column('skor_persepsi', sa.Integer(), nullable=False),
    sa.Column('kategori_persepsi', sa.String(length=20), nullable=False),
    sa.Column('skor_input', sa.Integer(), nullable=False),
    sa.Column('kategori_input', sa.String(length=20), nullable=False),
    sa.Column('skor_pemahaman', sa.Integer(), nullable=False),
    sa.Column('kategori_pemahaman', sa.String(length=20), nullable=False),
    sa.Column('id_rekomendasi_pemrosesan', sa.Integer(), nullable=True, comment='ID rekomendasi untuk kategori pemrosesan'),
    sa.Column('id_rekomendasi_persepsi', sa.Integer(), nullable=True, comment='ID rekomendasi untuk kategori persepsi'),
    sa.Column('id_rekomendasi_input', sa.Integer(), nullable=True, comment='ID rekomendasi untuk kategori input'),
    sa.Column('id_rekomendasi_pemahaman', sa.Integer(), nullable=True, comment='ID rekomendasi untuk kategori pemahaman'),
    sa.Column('dibuat_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rekomendasi_input'], ['rekomendasi_gaya_belajar.id'], ),
    sa.ForeignKeyConstraint(['id_rekomendasi_pemahaman'], ['rekomendasi_gaya_belajar.id'], ),
    sa.ForeignKeyConstraint(['id_rekomendasi_pemrosesan'], ['rekomendasi_gaya_belajar.id'], ),
    sa.ForeignKeyConstraint(['id_rekomendasi_persepsi'], ['rekomendasi_gaya_belajar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jawaban_pengguna',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.JSON(), nullable=False),
    sa.Column('dijawab_pada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reset_password',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('kadaluarsa_pada', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pengguna', sa.Integer(), nullable=False),
    sa.Column('nisn', sa.String(length=20), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=255), nullable=False),
    sa.Column('nomor_telepon', sa.String(length=20), nullable=False),
    sa.Column('tanggal_lahir', sa.Date(), nullable=False),
    sa.Column('jenis_kelamin', sa.String(length=20), nullable=False),
    sa.Column('kelas', sa.String(length=50), nullable=False),
    sa.Column('nama_sekolah', sa.String(length=255), nullable=False),
    sa.Column('penyandang_disabilitas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_pengguna'], ['pengguna.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_pengguna'),
    sa.UniqueConstraint('nisn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('siswa')
    op.drop_table('reset_password')
    op.drop_table('jawaban_pengguna')
    op.drop_table('hasil_gaya_belajar')
    op.drop_table('guru')
    op.drop_table('admin')
    op.drop_table('soal')
    op.drop_index('idx_nama_sekolah', table_name='sekolah')
    op.drop_table('sekolah')
    op.drop_index('idx_kategori_gaya', table_name='rekomendasi_gaya_belajar')
    op.drop_table('rekomendasi_gaya_belajar')
    op.drop_table('pengguna')
    # ### end Alembic commands ###
